# Generated by Django 6.0.2 on 2026-08-27 02:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integration', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable mapping profile name.', max_length=150)),
                ('target_entity', models.CharField(help_text='Target Canonical Standard Data Model entity (e.g. Order, Customer, ServiceRequest).', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mapping_profiles', to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(blank=True, help_text='Optional associated external data source.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping_profiles', to='integration.datasource')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'mapping_mappingprofile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MappingRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_field', models.CharField(help_text='Raw external column header name, formula expression, or source identifier.', max_length=100)),
                ('target_field', models.CharField(help_text='Canonical field name in Standard Data Model.', max_length=100)),
                ('rule_type', models.CharField(choices=[('FIELD_MAPPING', 'Field Mapping (Direct Rename)'), ('TYPE_CONVERSION', 'Type Conversion (Cast & Sanitize)'), ('VALUE_MAPPING', 'Value Mapping (Categorical / Code Lookup)'), ('BUSINESS_FORMULA', 'Business Formula (Safe Expression)'), ('AI_ASSISTED_MAPPING', 'AI-Assisted Mapping (Recommendation)')], db_index=True, default='FIELD_MAPPING', max_length=30)),
                ('transformation_config', models.JSONField(blank=True, default=dict, help_text="Transformation details: For TYPE_CONVERSION: {'target_type': 'DECIMAL', 'format': '%d/%m/%Y'}. For VALUE_MAPPING: {'value_map': {'raw': 'CANONICAL'}, 'default': 'DEFAULT'}. For BUSINESS_FORMULA: {'expression': 'unit_price * quantity - discount'}. For AI_ASSISTED_MAPPING: {'confidence': 0.94, 'reason': '...'}")),
                ('confidence_score', models.FloatField(default=1.0, help_text='Confidence rating (0.0 to 1.0) for AI-suggested mappings. Heuristic mappings default to 1.0.')),
                ('ai_status', models.CharField(choices=[('PENDING', 'Pending Human Review'), ('ACCEPTED', 'Accepted by Human'), ('REJECTED', 'Rejected by Human')], default='ACCEPTED', help_text='Human-in-the-loop review state. AI rules require explicit human acceptance.', max_length=20)),
                ('validation_status', models.CharField(choices=[('VALID', 'Valid'), ('INVALID', 'Invalid'), ('PENDING', 'Pending Validation')], default='VALID', max_length=20)),
                ('validation_error', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Execution precedence order.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mapping_rules', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='mapping.mappingprofile')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'mapping_mappingrule',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='mappingprofile',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_workspace_mapping_profile_name'),
        ),
        migrations.AddIndex(
            model_name='mappingrule',
            index=models.Index(fields=['profile', 'is_active'], name='mapping_map_profile_45f461_idx'),
        ),
        migrations.AddIndex(
            model_name='mappingrule',
            index=models.Index(fields=['workspace', 'rule_type'], name='mapping_map_workspa_721b67_idx'),
        ),
    ]
