# Generated by Django 6.0.2 on 2026-08-26 07:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_ops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hourly_labor_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('150000.00'), help_text='Standard hourly labor rate in VND for technician', max_digits=12),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('INSTALLATION', 'System Installation'), ('MAINTENANCE', 'System Maintenance'), ('DATABASE_CONSULTING', 'Database Consulting'), ('DEVICE_REPAIR', 'Device Repair')], db_index=True, default='INSTALLATION', max_length=50),
        ),
        migrations.CreateModel(
            name='LaborEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration of work in minutes')),
                ('hourly_rate_snapshot', models.DecimalField(decimal_places=2, help_text='Snapshot of technician hourly rate in VND at log time', max_digits=12)),
                ('labor_cost', models.DecimalField(decimal_places=2, help_text='Server-calculated total labor cost: (duration_minutes / 60) * hourly_rate_snapshot', max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labor_entries', to='service_ops.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_entries', to='service_ops.task')),
            ],
            options={
                'verbose_name': 'Labor Entry',
                'verbose_name_plural': 'Labor Entries',
                'db_table': 'service_ops_labor_entry',
                'ordering': ['-started_at'],
            },
        ),
    ]
