# Generated by Django 6.0.2 on 2026-08-26 12:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable name for this data source.', max_length=150)),
                ('source_type', models.CharField(choices=[('CSV', 'CSV File'), ('EXCEL', 'Excel Spreadsheet (.xlsx)'), ('MOCK_API', 'Mock External REST API')], max_length=20)),
                ('connection_config', models.JSONField(blank=True, default=dict, help_text='Safe configuration parameters (e.g. endpoint URL, sheet name, delimiter). Never store raw secrets.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_data_sources', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'integration_datasource',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('RETAIL_ORDERS', 'Retail Orders'), ('RETAIL_CUSTOMERS', 'Retail Customers'), ('RETAIL_PRODUCTS', 'Retail Products'), ('SERVICE_REQUESTS', 'Service Incident Tickets'), ('SERVICE_TECHNICIANS', 'Field Technicians'), ('GENERAL', 'General Dataset')], default='GENERAL', help_text='Expected business entity category for this import batch.', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partially Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('total_rows', models.IntegerField(default=0, help_text='Total rows identified in source file/payload.')),
                ('successful_rows', models.IntegerField(default=0, help_text='Rows parsed and staged successfully.')),
                ('failed_rows', models.IntegerField(default=0, help_text='Rows rejected due to structural or formatting errors.')),
                ('error_summary', models.JSONField(blank=True, default=list, help_text="List of error objects: [{'row': int, 'error_type': str, 'message': str, 'raw': dict}]")),
                ('source_file', models.FileField(blank=True, help_text='Archived raw input file.', null=True, upload_to='imports/%Y/%m/')),
                ('source_metadata', models.JSONField(blank=True, default=dict, help_text='Technical metadata: filename, file_size_bytes, columns, detected_encoding, sheet_name.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='integration.datasource')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'integration_importjob',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawImportRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField(help_text='1-indexed row number in the source file.')),
                ('raw_data', models.JSONField(default=dict, help_text='Unaltered raw dictionary extracted from the source row.')),
                ('is_valid', models.BooleanField(default=True, help_text='Whether this record passed structural and datatype checks at ingestion time.')),
                ('validation_errors', models.JSONField(blank=True, default=list, help_text='List of validation error messages encountered during ingestion.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='integration.importjob')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'integration_rawimportrecord',
                'ordering': ['row_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='datasource',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_workspace_datasource_name'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['workspace', 'status'], name='integration_workspa_cb99ab_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['data_source', 'status'], name='integration_data_so_b2ee6f_idx'),
        ),
        migrations.AddIndex(
            model_name='rawimportrecord',
            index=models.Index(fields=['import_job', 'row_number'], name='integration_import__63bb18_idx'),
        ),
        migrations.AddIndex(
            model_name='rawimportrecord',
            index=models.Index(fields=['import_job', 'is_valid'], name='integration_import__50ad2e_idx'),
        ),
    ]
