# Generated by Django 6.0.2 on 2026-08-27 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastModelConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('target_type', models.CharField(choices=[('RETAIL_REVENUE', 'Retail Revenue'), ('RETAIL_ORDER_VOLUME', 'Retail Order Volume'), ('SERVICE_TICKET_VOLUME', 'Service Ticket Volume')], db_index=True, max_length=50)),
                ('model_type', models.CharField(choices=[('XGBOOST_REGRESSOR', 'XGBoost Regressor')], default='XGBOOST_REGRESSOR', max_length=50)),
                ('granularity', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='DAILY', max_length=20)),
                ('feature_config', models.JSONField(blank=True, default=dict, help_text='Configuration for lag periods, rolling windows, and calendar features.')),
                ('training_config', models.JSONField(blank=True, default=dict, help_text='XGBoost hyperparameters: n_estimators, max_depth, learning_rate, subsample, test_size.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('model_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Forecast Model Config',
                'verbose_name_plural': 'Forecast Model Configs',
                'db_table': 'forecasting_model_config',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('RETAIL_REVENUE', 'Retail Revenue'), ('RETAIL_ORDER_VOLUME', 'Retail Order Volume'), ('SERVICE_TICKET_VOLUME', 'Service Ticket Volume')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('training_start_at', models.DateTimeField(blank=True, null=True)),
                ('training_end_at', models.DateTimeField(blank=True, null=True)),
                ('dataset_period_start', models.DateField(blank=True, null=True)),
                ('dataset_period_end', models.DateField(blank=True, null=True)),
                ('dataset_row_count', models.PositiveIntegerField(default=0)),
                ('train_row_count', models.PositiveIntegerField(default=0)),
                ('test_row_count', models.PositiveIntegerField(default=0)),
                ('model_metrics', models.JSONField(blank=True, default=dict, help_text='XGBoost test metrics: mae, rmse, mape, r2.')),
                ('baseline_metrics', models.JSONField(blank=True, default=dict, help_text='Naive persistence baseline metrics: naive_mae, naive_rmse, naive_mape.')),
                ('feature_importances', models.JSONField(blank=True, default=dict, help_text='Feature importance scores extracted from XGBoost.')),
                ('artifact_path', models.CharField(blank=True, help_text='Relative path to serialized model artifact within ml_models/forecasting/.', max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_runs', to=settings.AUTH_USER_MODEL)),
                ('model_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='forecasting.forecastmodelconfig')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Forecast Run',
                'verbose_name_plural': 'Forecast Runs',
                'db_table': 'forecasting_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('RETAIL_REVENUE', 'Retail Revenue'), ('RETAIL_ORDER_VOLUME', 'Retail Order Volume'), ('SERVICE_TICKET_VOLUME', 'Service Ticket Volume')], db_index=True, max_length=50)),
                ('forecast_date', models.DateField(db_index=True)),
                ('predicted_value', models.DecimalField(decimal_places=2, help_text='Point prediction generated by model.', max_digits=16)),
                ('lower_bound', models.DecimalField(blank=True, decimal_places=2, help_text='Lower interval bound (e.g. 95% confidence).', max_digits=16, null=True)),
                ('upper_bound', models.DecimalField(blank=True, decimal_places=2, help_text='Upper interval bound (e.g. 95% confidence).', max_digits=16, null=True)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, help_text='Actual observed value when backtesting.', max_digits=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
                ('forecast_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='forecasting.forecastrun')),
            ],
            options={
                'verbose_name': 'Forecast Result',
                'verbose_name_plural': 'Forecast Results',
                'db_table': 'forecasting_result',
                'ordering': ['forecast_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='forecastmodelconfig',
            constraint=models.UniqueConstraint(fields=('workspace', 'target_type', 'model_version'), name='unique_workspace_target_model_version'),
        ),
        migrations.AddConstraint(
            model_name='forecastresult',
            constraint=models.UniqueConstraint(fields=('forecast_run', 'forecast_date'), name='unique_run_forecast_date'),
        ),
    ]
