# Generated by Django 6.0.2 on 2026-09-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastmodelconfig',
            name='target_type',
            field=models.CharField(choices=[('RETAIL_REVENUE', 'Retail Revenue'), ('RETAIL_ORDER_VOLUME', 'Retail Order Volume'), ('RETAIL_PRODUCT_DEMAND', 'Retail Product Demand'), ('SERVICE_TICKET_VOLUME', 'Service Ticket Volume')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='forecastresult',
            name='target_type',
            field=models.CharField(choices=[('RETAIL_REVENUE', 'Retail Revenue'), ('RETAIL_ORDER_VOLUME', 'Retail Order Volume'), ('RETAIL_PRODUCT_DEMAND', 'Retail Product Demand'), ('SERVICE_TICKET_VOLUME', 'Service Ticket Volume')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='forecastrun',
            name='target_type',
            field=models.CharField(choices=[('RETAIL_REVENUE', 'Retail Revenue'), ('RETAIL_ORDER_VOLUME', 'Retail Order Volume'), ('RETAIL_PRODUCT_DEMAND', 'Retail Product Demand'), ('SERVICE_TICKET_VOLUME', 'Service Ticket Volume')], db_index=True, max_length=50),
        ),
    ]
