# Generated by Django 6.0.2 on 2026-08-27 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('proposed_action', models.CharField(db_index=True, help_text='Whitelisted tool name (e.g. dispatch_technician, update_order_status).', max_length=100)),
                ('parameters', models.JSONField(default=dict, help_text='Validated JSON payload parameters for tool execution.')),
                ('reason', models.TextField(help_text='Business justification or AI explanation for requesting the mutation.')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], db_index=True, default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('EXECUTED', 'Executed')], db_index=True, default='PENDING', max_length=20)),
                ('review_timestamp', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Unique key preventing duplicate replay execution of the mutation.', max_length=100)),
                ('execution_result', models.JSONField(blank=True, help_text='Cached execution output payload stored after success.', null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('requester', models.ForeignKey(help_text='User who initiated or requested the mutation action.', on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests_submitted', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, help_text='Authorized manager/admin who approved or rejected the request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Approval Request',
                'verbose_name_plural': 'Approval Requests',
                'db_table': 'approvals_approvalrequest',
                'ordering': ['-created_at'],
                'permissions': [('manage_approval', 'Can approve or reject mutation requests')],
            },
        ),
    ]
