# Generated by Django 6.0.2 on 2026-09-06 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.UniqueConstraint(fields=('workspace', 'idempotency_key'), name='unique_workspace_approval_key'),
        ),
    ]
