# Generated by Django 6.0.2 on 2026-08-27 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(choices=[('RETAIL_DECLINING_REVENUE', 'Declining Branch Revenue'), ('RETAIL_LOW_ORDER_VOLUME', 'Low Order Volume Alert'), ('RETAIL_HIGH_PERFORMING', 'High Performing Branch Practice Sharing'), ('SERVICE_SLA_AT_RISK', 'SLA Breach Risk Alert'), ('SERVICE_TECHNICIAN_OVERLOAD', 'Technician Workload Imbalance'), ('SERVICE_TICKET_SPIKE', 'Service Ticket Volume Spike'), ('SERVICE_NEARBY_TECHNICIAN', 'Nearby Technician Dispatch Candidate')], db_index=True, max_length=60)),
                ('title', models.CharField(max_length=255)),
                ('explanation', models.JSONField(default=dict, help_text="Structured explanation schema containing 'what', 'why', 'evidence', and 'expected_effect'.")),
                ('supporting_data', models.JSONField(blank=True, default=dict, help_text='Raw metrics, forecast outputs, or GIS proximity payload supporting the recommendation.')),
                ('source_references', models.JSONField(blank=True, default=list, help_text='List of source entity URIs/IDs (e.g. branch_id, ticket_id, forecast_run_id).')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User actor or None for system-generated rules.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recommendations', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'db_table': 'recommendations_recommendation',
                'ordering': ['-created_at'],
                'permissions': [('manage_recommendation', 'Can accept, reject or trigger recommendations')],
            },
        ),
    ]
