# Generated by Django 6.0.2 on 2026-09-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='recommendation_type',
            field=models.CharField(choices=[('RETAIL_DECLINING_REVENUE', 'Declining Branch Revenue'), ('RETAIL_LOW_ORDER_VOLUME', 'Low Order Volume Alert'), ('RETAIL_HIGH_PERFORMING', 'High Performing Branch Practice Sharing'), ('RETAIL_STOCKOUT_RISK', 'Retail Stockout Risk Alert'), ('SERVICE_SLA_AT_RISK', 'SLA Breach Risk Alert'), ('SERVICE_TECHNICIAN_OVERLOAD', 'Technician Workload Imbalance'), ('SERVICE_TICKET_SPIKE', 'Service Ticket Volume Spike'), ('SERVICE_NEARBY_TECHNICIAN', 'Nearby Technician Dispatch Candidate')], db_index=True, max_length=60),
        ),
    ]
