# Generated by Django 6.0.2 on 2026-09-06 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0005_customer_account_identity'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reference_number', models.CharField(db_index=True, max_length=60)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('EXECUTED', 'Executed'), ('CANCELLED', 'Cancelled'), ('ROLLED_BACK', 'Rolled Back')], db_index=True, default='EXECUTED', max_length=20)),
                ('idempotency_key', models.CharField(db_index=True, max_length=120)),
                ('rollback_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('destination_branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='incoming_stock_transfers', to='retail.branch')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_stock_transfers', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stock_transfers', to='retail.product')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_stock_transfers', to=settings.AUTH_USER_MODEL)),
                ('source_branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='outgoing_stock_transfers', to='retail.branch')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'retail_stocktransfer',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='retail_stoc_workspa_bf8b66_idx'), models.Index(fields=['workspace', 'source_branch'], name='retail_stoc_workspa_4a48d2_idx'), models.Index(fields=['workspace', 'destination_branch'], name='retail_stoc_workspa_c25c6f_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'reference_number'), name='unique_workspace_stock_transfer_ref'), models.UniqueConstraint(fields=('workspace', 'idempotency_key'), name='unique_workspace_stock_transfer_key'), models.CheckConstraint(condition=models.Q(('source_branch', models.F('destination_branch')), _negated=True), name='stock_transfer_distinct_branches')],
            },
        ),
    ]
