# Generated by Django 6.0.2 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0006_stocktransfer"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="fulfillment_stock_reserved",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="fulfillment_stock_released_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
