# Generated by Django 6.0.2 on 2026-09-03 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('NEW_CUSTOMER', 'Khách hàng mới'), ('NEW_ORDER', 'Đơn hàng mới'), ('NEW_SERVICE_REQUEST', 'Yêu cầu dịch vụ mới'), ('NEW_CONTACT', 'Liên hệ mới')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('entity_type', models.CharField(blank=True, max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=100)),
                ('target_url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'workspace', 'is_read', '-created_at'], name='notificatio_recipie_b5203e_idx'), models.Index(fields=['workspace', 'event_type', '-created_at'], name='notificatio_workspa_7b7124_idx')],
            },
        ),
    ]
