# Generated by Django 6.0.2 on 2026-09-12 01:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('NEW_CUSTOMER', 'Khách hàng mới'), ('NEW_ORDER', 'Đơn hàng mới'), ('NEW_SERVICE_REQUEST', 'Yêu cầu dịch vụ mới'), ('NEW_CONTACT', 'Liên hệ mới'), ('CUSTOMER_ORDER_APPROVED', 'Đơn hàng của bạn đã được duyệt'), ('CUSTOMER_SERVICE_APPROVED', 'Yêu cầu dịch vụ đã được tiếp nhận')], db_index=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('event_type__in', ['CUSTOMER_ORDER_APPROVED', 'CUSTOMER_SERVICE_APPROVED'])), fields=('workspace', 'recipient', 'event_type', 'entity_type', 'entity_id'), name='unique_customer_approval_notice'),
        ),
    ]
