# Generated by Django 6.0.2 on 2026-09-22 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_customer_approval_notices'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalBulletin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('NORMAL', 'Thông thường'), ('URGENT', 'Khẩn cấp'), ('PINNED', 'Ghim đầu trang')], db_index=True, default='NORMAL', max_length=20)),
                ('pinned_until', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_bulletins', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Internal Bulletin',
                'verbose_name_plural': 'Internal Bulletins',
                'db_table': 'notifications_internal_bulletin',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'is_published', '-created_at'], name='notificatio_workspa_776aef_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeamChatMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_team_messages', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_chat_messages', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Team Chat Message',
                'verbose_name_plural': 'Team Chat Messages',
                'db_table': 'notifications_team_chat_message',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['workspace', 'created_at'], name='notificatio_workspa_6cc009_idx'), models.Index(fields=['workspace', '-id'], name='notificatio_workspa_e1b00f_idx')],
            },
        ),
    ]
